version: '3.8'
services:
  redis:
    image: redis:7.2.1
    ports:
      - "6379:6379"
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  manager:
    image: python:3.10-slim
    command: python -c "print('Manager ready')"
  worker:
    image: wisrovi/train_service:worker_executor_v1.0.0
    deploy:
      resources:
        limits:
          memory: 11g
    shm_size: '8gb'
